pickaxe: #настройки кирки
  material: GOLDEN_PICKAXE #материал. вы можете выбрать любой предмет, желательно кирку
  display-name: '&#ffdd00Золотая Кирка Джейка' #отоброжаемое имя
  lore: #описание
    - ' '
    - '&8Особенности:'
    - ' &f- позволяет забрать спавнер'
    - ' &f  с мобом внутри'
    - ' '

spawner: #настройки спавнеров
  display-name: '&fРассадник %mobname%' #отоброжаемое имя
  lore: [] #описание
  sound: ENTITY_ARROW_HIT_PLAYER #звук при добычи спавнера киркой

mobs: #русификация айди мобов (не трогайте, если не знаете что это)
  ALLAY: 'тихони'
  AXOLOTL: 'аксолотля'
  BAT: 'летучей мыши'
  BEE: 'пчелы'
  BLAZE: 'блейза'
  CAMEL: 'верблюда'
  CAT: 'кошки'
  CAVE_SPIDER: 'пещерного паука'
  CHICKEN: 'курицы'
  COD: 'трески'
  COW: 'коровы'
  CREEPER: 'крипера'
  DOLPHIN: 'дельфина'
  DONKEY: 'осла'
  DROWNED: 'утопленника'
  ELDER_GUARDIAN: 'старшего стража'
  ENDER_DRAGON: 'эндер-дракона'
  ENDER_MAN: 'эндермена'
  ENDERMITE: 'эндермита'
  EVOKER: 'заклинателя'
  FOX: 'лисы'
  FROG: 'лягушки'
  GHAST: 'гаста'
  GIANT: 'гиганта'
  GLOW_SQUID: 'светящегося спрута'
  GOAT: 'козла'
  GUARDIAN: 'стража'
  HORSE: 'лошади'
  HOGLIN: 'хоглина'
  HUSK: 'кадавра'
  ILLUSIONER: 'иллюзионера'
  IRON_GOLEM: 'железного голема'
  KILLER_BUNNY: 'убийственного кролика'
  LLAMA: 'ламы'
  MAGMA_CUBE: 'магмового куба'
  MUSHROOM_COW: 'муухомора'
  MULE: 'мула'
  OCELOT: 'оцелота'
  PANDA: 'панды'
  PARROT: 'попугая'
  PHANTOM: 'фантома'
  PIG: 'свиньи'
  PIGLIN: 'пиглина'
  PIGLIN_BRUTE: 'брутального пиглина'
  PILLAGER: 'разбойника'
  POLAR_BEAR: 'белого медведя'
  PUFFERFISH: 'иглобрюха'
  RABBIT: 'кролика'
  RAVAGER: 'разорителя'
  SALMON: 'лосося'
  SHEEP: 'овцы'
  SHULKER: 'шалкера'
  SILVERFISH: 'чешуйницы'
  SKELETON: 'скелета'
  SKELETON_HORSE: 'лошади-скелета'
  SLIME: 'слизня'
  SNOWMAN: 'снежного голема'
  SNIFFER: 'нюхача'
  SPIDER: 'паука'
  SQUID: 'спрута'
  STRAY: 'зимогор'
  STRIDER: 'лавомерки'
  TADPOLE: 'головастика'
  TRADER_LLAMA: 'ламы торговца'
  TROPICAL_FISH: 'тропической рыбы'
  TURTLE: 'черепахи'
  VEX: 'вредины'
  VILLAGER: 'жителя'
  VINDICATOR: 'поборника'
  WANDERING_TRADER: 'бродячего торговца'
  WARDEN: 'вардена'
  WITCH: 'ведьмы'
  WITHER: 'визера'
  WITHER_SKELETON: 'визер-скелета'
  WOLF: 'волка'
  ZOGLIN: 'зоглина'
  ZOMBIE: 'зомби'
  ZOMBIE_HORSE: 'зомби-лошади'
  ZOMBIE_VILLAGER: 'зомби-жителя'
  ZOMBIFIED_PIGLIN: 'зомбифицированного пиглина'
