name: JaycobPickaxe
version: '${project.version}'
main: me.chi2l3s.jaycobpickaxe.JaycobPickaxe
api-version: '1.16'
softdepend:
  - PlaceholderAPI
commands:
  jp:
    description: PON
    usage: /<command> <subcommand> [args...]
    aliases:
      - jakepickaxe
      - goldenpickaxe
      - spawnerpicaxe
